### ISSUE TITLE
Query patient demographics from symptoms and procedures

### ISSUE THREAD

**Issue by awatson1978** [symptomatic/covid19-on-fhir#5]

**Comment by awatson1978** [comment]
![Screen Shot 2020-03-25 at 3 31 48 PM](https://user-images.githubusercontent.com/675910/77587815-a59f3880-6eb6-11ea-9f7d-a03748d47a6b.png)

Success!  

No address data though.  Logged a comment on https://github.com/synthetichealth/synthea/issues/679

**Comment by jawalonoski** [comment]
I just ran the Synthea `covid19` branch code locally, and I'm seeing Patient addresses. Is it possible they are being dropped during insertion into HAPI?

**Comment by awatson1978** [comment]
It's very possible.  I'll investigated and see what options we have for other utility uploaders.

**Comment by awatson1978** [comment]
Looks like it might have been something with the HAPI server; possibly being overly restrictive with validation and/or me mis-loading DSTU2 data into an R4 server.  The new `https://covid19-under-fhir.smilecdr.com` seems to be receiving the data fine.  

Confirming the following.  
```
// R4 Encounters - Has class 
https://covid19-under-fhir.smilecdr.com/baseR4/Encounter?type=185345009

// R4 Patient - Has Address
https://covid19-under-fhir.smilecdr.com/baseR4/Patient/1b0580b9-1ee3-4353-b555-64c797d57564
```

We can close.
